---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-mtls
  labels:
    name: default-mtls
    app: ms
  namespace: ms-ns
spec:
  mtls:
    mode: STRICT

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-dr
  labels:
    name: default-dr
    app: ms
  namespace: ms-ns
spec:
  host: msfrontend-svc.ms-ns.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
