---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opa-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:opa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-modifier
  namespace: opa-ns
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opa-configmap-modifier
  namespace: opa-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-modifier
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:opa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa
  name: opa
  namespace: opa-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      volumes:
      - name: opa-vol
        secret:
          secretName: opa-secret
      containers:
      - name: opa
        image: openpolicyagent/opa:0.39.0-rootless
        args:
        - run
        - --server
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key=/certs/tls.key
        - --addr=0.0.0.0:8443
        - --insecure-addr=http://127.0.0.1:8181
        - --log-format=json-pretty
        - --set=decision_logs.console=true
        - --set=status.console=true
        readinessProbe:
            httpGet:
              path: /health?plugins&bundle
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 5
        livenessProbe:
            httpGet:
              path: /health
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 5
        volumeMounts:
        - name: opa-vol
          mountPath: /certs
          readOnly: true
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:4.1.0
        args:
        - --replicate-cluster=v1/namespaces
        - --replicate=v1/pods
