name: Deploy
on:
  push:
    branches:
    - release
    tags:
    - 'v*'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  run-this:
    runs-on: ubuntu-latest
    steps:
    - name: echo date
      run: echo ">>> ${BRANCH_NAME}: The current date is $(date)"
